### ISSUE TITLE
"s and 's are over-escaped

### ISSUE THREAD

**Issue by domenic** [cheeriojs/dom-serializer#15] opened 2014-09-13 14:31 UTC
E.g. using Cheerio, `$('<code>"hello"</code>').html()` gives back `&quot;hello&quot;`, which is unnecessarily ugly and doesn't match browsers.

**Comment by fb55** [comment] 2015-02-11 22:28
Duplicate of #1.

**Closed by fb55** 2015-02-11 22:28 UTC
